USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE YELP_DB;

CREATE SCHEMA IF NOT EXISTS CLEAN;

CREATE OR REPLACE TASK YELP_DB.CLEAN.TASK_REFRESH_CHECKIN_EVENTS_CLEAN
  WAREHOUSE = COMPUTE_WH
  AFTER YELP_DB.CLEAN.TASK_REFRESH_BUSINESS_CLEAN
AS
CREATE OR REPLACE TABLE YELP_DB.CLEAN.CHECKIN_EVENTS_CLEAN AS
SELECT
    BUSINESS_ID,
    CHECKIN_TIME,
    CHECKIN_DATE,
    CHECKIN_MONTH
FROM (
    SELECT
        BUSINESS_ID,
        TO_TIMESTAMP(TRIM(value::STRING)) AS CHECKIN_TIME,
        TO_DATE(TO_TIMESTAMP(TRIM(value::STRING))) AS CHECKIN_DATE,
        DATE_TRUNC('MONTH', TO_DATE(TO_TIMESTAMP(TRIM(value::STRING)))) AS CHECKIN_MONTH,
        ROW_NUMBER() OVER (
            PARTITION BY BUSINESS_ID, TO_TIMESTAMP(TRIM(value::STRING))
            ORDER BY TO_TIMESTAMP(TRIM(value::STRING))
        ) AS rn
    FROM YELP_DB.RAW.YELP_CHECKIN,
         LATERAL FLATTEN(INPUT => SPLIT(DATE, ','))
    WHERE BUSINESS_ID IS NOT NULL
      AND DATE IS NOT NULL
      AND TRIM(value::STRING) <> ''
)
WHERE rn = 1;

ALTER TASK YELP_DB.CLEAN.TASK_REFRESH_CHECKIN_EVENTS_CLEAN RESUME;
ALTER TASK YELP_DB.CLEAN.TASK_REFRESH_BUSINESS_CLEAN RESUME; 



SHOW TASKS IN SCHEMA YELP_DB.CLEAN;

SELECT *
FROM TABLE(
    YELP_DB.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_REFRESH_CHECKIN_EVENTS_CLEAN',
        RESULT_LIMIT => 10
    )
);


SHOW TABLES IN SCHEMA YELP_DB.CLEAN;