USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE YELP_DB;
USE SCHEMA RAW;


--clean checkin--
CREATE SCHEMA IF NOT EXISTS CLEAN;

CREATE OR REPLACE TABLE YELP_DB.CLEAN.CHECKIN_CLEAN AS
SELECT
    BUSINESS_ID,
    CHECKIN_RAW,
    CHECKIN_COUNT_EST
FROM (
    SELECT
        BUSINESS_ID,
        TRIM(DATE) AS CHECKIN_RAW,
        CASE
            WHEN DATE IS NULL OR TRIM(DATE) = '' THEN 0
            ELSE REGEXP_COUNT(TRIM(DATE), ',') + 1
        END AS CHECKIN_COUNT_EST,
        ROW_NUMBER() OVER (
            PARTITION BY BUSINESS_ID, TRIM(DATE)
            ORDER BY BUSINESS_ID
        ) AS rn
    FROM YELP_DB.RAW.YELP_CHECKIN
    WHERE BUSINESS_ID IS NOT NULL
)
WHERE rn = 1;

-- 分表，checkin_event
CREATE OR REPLACE TABLE YELP_DB.CLEAN.CHECKIN_EVENTS_CLEAN AS
SELECT
    BUSINESS_ID,
    CHECKIN_TIME,
    CHECKIN_DATE,
    CHECKIN_MONTH
FROM (
    SELECT
        BUSINESS_ID,
        TO_TIMESTAMP(TRIM(value::STRING)) AS CHECKIN_TIME,
        TO_DATE(TO_TIMESTAMP(TRIM(value::STRING))) AS CHECKIN_DATE,
        DATE_TRUNC('MONTH', TO_DATE(TO_TIMESTAMP(TRIM(value::STRING)))) AS CHECKIN_MONTH,
        ROW_NUMBER() OVER (
            PARTITION BY BUSINESS_ID, TO_TIMESTAMP(TRIM(value::STRING))
            ORDER BY TO_TIMESTAMP(TRIM(value::STRING))
        ) AS rn
    FROM YELP_DB.RAW.YELP_CHECKIN,
         LATERAL FLATTEN(INPUT => SPLIT(DATE, ','))
    WHERE BUSINESS_ID IS NOT NULL
      AND DATE IS NOT NULL
      AND TRIM(value::STRING) <> ''
)
WHERE rn = 1;
