USE DATABASE YELP_DB;
USE SCHEMA RAW;

-- ============================================
-- 1. PUB/SUB NOTIFICATION INTEGRATION
-- ============================================

CREATE OR REPLACE NOTIFICATION INTEGRATION GCS_YELP_NOTIFY
TYPE = QUEUE
NOTIFICATION_PROVIDER = GCP_PUBSUB
ENABLED = TRUE
GCP_PUBSUB_SUBSCRIPTION_NAME = 'projects/final-project-489422/subscriptions/yelp-parquet-updates-sub';

DESC NOTIFICATION INTEGRATION GCS_YELP_NOTIFY;

-- ============================================
-- 2. GCS STORAGE INTEGRATION
-- ============================================

CREATE OR REPLACE STORAGE INTEGRATION GCP_GCS_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = GCS
ENABLED = TRUE
STORAGE_ALLOWED_LOCATIONS = ('gcs://msba405-yelp-data/');

DESC STORAGE INTEGRATION GCP_GCS_INT;

-- ============================================
-- 3. STAGES
-- ============================================

CREATE OR REPLACE STAGE YELP_DB.RAW.YELP_BUSINESS_STAGE
URL = 'gcs://msba405-yelp-data/processed/parquet/business/'
STORAGE_INTEGRATION = GCP_GCS_INT
FILE_FORMAT = (TYPE = PARQUET);

CREATE OR REPLACE STAGE YELP_DB.RAW.YELP_REVIEW_STAGE
URL = 'gcs://msba405-yelp-data/processed/parquet/review/'
STORAGE_INTEGRATION = GCP_GCS_INT
FILE_FORMAT = (TYPE = PARQUET);

CREATE OR REPLACE STAGE YELP_DB.RAW.YELP_USER_STAGE
URL = 'gcs://msba405-yelp-data/processed/parquet/user/'
STORAGE_INTEGRATION = GCP_GCS_INT
FILE_FORMAT = (TYPE = PARQUET);

CREATE OR REPLACE STAGE YELP_DB.RAW.YELP_CHECKIN_STAGE
URL = 'gcs://msba405-yelp-data/processed/parquet/checkin/'
STORAGE_INTEGRATION = GCP_GCS_INT
FILE_FORMAT = (TYPE = PARQUET);

CREATE OR REPLACE STAGE YELP_DB.RAW.YELP_TIP_STAGE
URL = 'gcs://msba405-yelp-data/processed/parquet/tip/'
STORAGE_INTEGRATION = GCP_GCS_INT
FILE_FORMAT = (TYPE = PARQUET);

-- ============================================
-- 4. VERIFY STAGES CAN READ FILES
-- ============================================

LIST @YELP_DB.RAW.YELP_BUSINESS_STAGE;
LIST @YELP_DB.RAW.YELP_REVIEW_STAGE;
LIST @YELP_DB.RAW.YELP_USER_STAGE;
LIST @YELP_DB.RAW.YELP_CHECKIN_STAGE;
LIST @YELP_DB.RAW.YELP_TIP_STAGE;

-- ============================================
-- 5. PIPES (AUTO INGEST)
-- NOTE: uses GCS_YELP_NOTIFY, not GCP_PUBSUB_INT
-- ============================================

CREATE OR REPLACE PIPE YELP_DB.RAW.PIPE_YELP_BUSINESS
AUTO_INGEST = TRUE
INTEGRATION = 'GCS_YELP_NOTIFY'
AS
COPY INTO YELP_DB.RAW.YELP_BUSINESS
FROM @YELP_DB.RAW.YELP_BUSINESS_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'SKIP_FILE';

CREATE OR REPLACE PIPE YELP_DB.RAW.PIPE_YELP_REVIEW
AUTO_INGEST = TRUE
INTEGRATION = 'GCS_YELP_NOTIFY'
AS
COPY INTO YELP_DB.RAW.YELP_REVIEW
FROM @YELP_DB.RAW.YELP_REVIEW_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'SKIP_FILE';

CREATE OR REPLACE PIPE YELP_DB.RAW.PIPE_YELP_USER
AUTO_INGEST = TRUE
INTEGRATION = 'GCS_YELP_NOTIFY'
AS
COPY INTO YELP_DB.RAW.YELP_USER
FROM @YELP_DB.RAW.YELP_USER_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'SKIP_FILE';

CREATE OR REPLACE PIPE YELP_DB.RAW.PIPE_YELP_CHECKIN
AUTO_INGEST = TRUE
INTEGRATION = 'GCS_YELP_NOTIFY'
AS
COPY INTO YELP_DB.RAW.YELP_CHECKIN
FROM @YELP_DB.RAW.YELP_CHECKIN_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'SKIP_FILE';

CREATE OR REPLACE PIPE YELP_DB.RAW.PIPE_YELP_TIP
AUTO_INGEST = TRUE
INTEGRATION = 'GCS_YELP_NOTIFY'
AS
COPY INTO YELP_DB.RAW.YELP_TIP
FROM @YELP_DB.RAW.YELP_TIP_STAGE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'SKIP_FILE';

-- ============================================
-- 6. CHECK PIPE STATUS
-- ============================================

SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_BUSINESS');
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_REVIEW');
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_USER');
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_CHECKIN');
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_TIP');

-- ============================================
-- 7. OPTIONAL: LOAD EXISTING FILES ONCE
-- Use this only if parquet files already existed
-- before the pipes were created
-- ============================================

ALTER PIPE YELP_DB.RAW.PIPE_YELP_BUSINESS REFRESH;
ALTER PIPE YELP_DB.RAW.PIPE_YELP_REVIEW REFRESH;
ALTER PIPE YELP_DB.RAW.PIPE_YELP_USER REFRESH;
ALTER PIPE YELP_DB.RAW.PIPE_YELP_CHECKIN REFRESH;
ALTER PIPE YELP_DB.RAW.PIPE_YELP_TIP REFRESH;