-- GCP to Snowflake RAW 验证：--
--1. stage能不能看到文件
--2. pipe状态是不是正常
--3. 有没有报错文件

--1. Verify if stage can read GCS file or not
LIST @YELP_DB.RAW.YELP_BUSINESS_STAGE;
LIST @YELP_DB.RAW.YELP_REVIEW_STAGE;
LIST @YELP_DB.RAW.YELP_USER_STAGE;
LIST @YELP_DB.RAW.YELP_CHECKIN_STAGE;
LIST @YELP_DB.RAW.YELP_TIP_STAGE;

--2. check pipeline status
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_BUSINESS');
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_REVIEW');
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_USER');
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_CHECKIN');
SELECT SYSTEM$PIPE_STATUS('YELP_DB.RAW.PIPE_YELP_TIP');

--3. check if RAW table has loading history
--use business_clean as an example
USE DATABASE YELP_DB;
SELECT *
FROM TABLE(
  YELP_DB.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'YELP_DB.RAW.YELP_BUSINESS',
    START_TIME => DATEADD('day', -14, CURRENT_TIMESTAMP()),
    PIPE_NAME => 'YELP_DB.RAW.PIPE_YELP_BUSINESS'
  )
)
ORDER BY LAST_LOAD_TIME DESC;