SHOW TASKS IN SCHEMA YELP_DB.CLEAN;

--business_clean_check
EXECUTE TASK YELP_DB.CLEAN.TASK_REFRESH_BUSINESS_CLEAN;

SELECT *
FROM TABLE(
    YELP_DB.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_REFRESH_BUSINESS_CLEAN',
        RESULT_LIMIT => 20
    )
);

--phlida check__
SELECT *
FROM TABLE(
    YELP_DB.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_REFRESH_PHILADELPHIA_TOP_BUSINESSES',
        RESULT_LIMIT => 20
    )
);

--checkin_event_check--
EXECUTE TASK YELP_DB.CLEAN.TASK_REFRESH_BUSINESS_CLEAN;
SELECT *
FROM TABLE(
    YELP_DB.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_REFRESH_CHECKIN_EVENTS_CLEAN',
        RESULT_LIMIT => 20
    )
);


--review_clean_check--
EXECUTE TASK YELP_DB.CLEAN.TASK_REFRESH_BUSINESS_CLEAN;
SELECT * FROM TABLE(
    YELP_DB.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_REFRESH_REVIEW_CLEAN'
    )
);


SELECT COUNT(*) FROM YELP_DB.RAW.YELP_BUSINESS;

SELECT * FROM YELP_DB.RAW.YELP_BUSINESS LIMIT 10;

SELECT * FROM YELP_DB.CLEAN.BUSINESS_CLEAN;

SELECT COUNT(*) FROM YELP_DB.CLEAN.BUSINESS_CLEAN;

SELECT COUNT(*) FROM YELP_DB.CLEAN.PHILADELPHIA_TOP_BUSINESSES;


SELECT
  REVIEW_MONTH,
  COUNT(*) AS review_count,
  AVG(REVIEW_STARS)
FROM YELP_DB.CLEAN.REVIEW_CLEAN
GROUP BY REVIEW_MONTH;