CREATE OR REPLACE TASK YELP_DB.CLEAN.TASK_REFRESH_REVIEW_CLEAN
  WAREHOUSE = COMPUTE_WH
  AFTER YELP_DB.CLEAN.TASK_REFRESH_BUSINESS_CLEAN
AS

CREATE OR REPLACE TABLE YELP_DB.CLEAN.REVIEW_CLEAN AS
SELECT
    REVIEW_ID,
    USER_ID,
    BUSINESS_ID,
    REVIEW_STARS,
    USEFUL,
    FUNNY,
    COOL,
    REVIEW_TEXT,
    REVIEW_TIMESTAMP,
    REVIEW_DATE,
    REVIEW_MONTH,
    REVIEW_YEAR
FROM (
    SELECT
        REVIEW_ID,
        USER_ID,
        BUSINESS_ID,
        STARS AS REVIEW_STARS,
        USEFUL,
        FUNNY,
        COOL,
        TEXT AS REVIEW_TEXT,
        COALESCE(DATE_TS, TO_TIMESTAMP(DATE)) AS REVIEW_TIMESTAMP,
        TO_DATE(COALESCE(DATE_TS, TO_TIMESTAMP(DATE))) AS REVIEW_DATE,
        DATE_TRUNC('MONTH', COALESCE(DATE_TS, TO_TIMESTAMP(DATE))) AS REVIEW_MONTH,
        DATE_PART(YEAR, COALESCE(DATE_TS, TO_TIMESTAMP(DATE))) AS REVIEW_YEAR,
        ROW_NUMBER() OVER (
            PARTITION BY REVIEW_ID
            ORDER BY COALESCE(DATE_TS, TO_TIMESTAMP(DATE)) DESC
        ) AS rn
    FROM YELP_DB.RAW.YELP_REVIEW
    WHERE REVIEW_ID IS NOT NULL
      AND USER_ID IS NOT NULL
      AND BUSINESS_ID IS NOT NULL
)
WHERE rn = 1;


ALTER TASK YELP_DB.CLEAN.TASK_REFRESH_PHILADELPHIA_TOP_BUSINESSES RESUME;
ALTER TASK YELP_DB.CLEAN.TASK_REFRESH_CHECKIN_EVENTS_CLEAN RESUME;
ALTER TASK YELP_DB.CLEAN.TASK_REFRESH_REVIEW_CLEAN RESUME;
ALTER TASK YELP_DB.CLEAN.TASK_REFRESH_BUSINESS_CLEAN RESUME;
