USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE YELP_DB;
USE SCHEMA RAW;

SELECT
    COUNT(*) AS total_rows,
    COUNT_IF(REVIEW_ID IS NULL) AS missing_review_id,
    COUNT_IF(USER_ID IS NULL) AS missing_user_id,
    COUNT_IF(BUSINESS_ID IS NULL) AS missing_business_id,
    COUNT_IF(STARS IS NULL) AS missing_stars,
    COUNT_IF(DATE IS NULL) AS missing_date,
    COUNT_IF(DATE_TS IS NULL) AS missing_date_ts,
    COUNT_IF(TEXT IS NULL) AS missing_text
FROM YELP_REVIEW;


CREATE OR REPLACE TABLE YELP_DB.CLEAN.REVIEW_CLEAN AS
SELECT
    REVIEW_ID,
    USER_ID,
    BUSINESS_ID,
    REVIEW_STARS,
    USEFUL,
    FUNNY,
    COOL,
    REVIEW_TEXT,
    REVIEW_TIMESTAMP,
    REVIEW_DATE,
    REVIEW_MONTH,
    REVIEW_YEAR
FROM (
    SELECT
        REVIEW_ID,
        USER_ID,
        BUSINESS_ID,
        STARS AS REVIEW_STARS,
        USEFUL,
        FUNNY,
        COOL,
        TEXT AS REVIEW_TEXT,
        COALESCE(DATE_TS, TO_TIMESTAMP(DATE)) AS REVIEW_TIMESTAMP,
        TO_DATE(COALESCE(DATE_TS, TO_TIMESTAMP(DATE))) AS REVIEW_DATE,
        DATE_TRUNC('MONTH', COALESCE(DATE_TS, TO_TIMESTAMP(DATE))) AS REVIEW_MONTH,
        DATE_PART(YEAR, COALESCE(DATE_TS, TO_TIMESTAMP(DATE))) AS REVIEW_YEAR,
        ROW_NUMBER() OVER (
            PARTITION BY REVIEW_ID
            ORDER BY COALESCE(DATE_TS, TO_TIMESTAMP(DATE)) DESC
        ) AS rn
    FROM YELP_DB.RAW.YELP_REVIEW
    WHERE REVIEW_ID IS NOT NULL
      AND USER_ID IS NOT NULL
      AND BUSINESS_ID IS NOT NULL
)
WHERE rn = 1;

